version: '3'
services:
  server:
    build: ./server
    ports:
      - "${SERVER_PORT:-5000}:5000"
    environment:
      - FLASK_ENV=development
      - SERVER_PORT=${SERVER_PORT:-5000}
    networks:
      - internal

  mock-client:
    build: ./mock-client
    environment:
      - SERVER_URL=http://server:${SERVER_PORT:-5000}
    depends_on:
      - server
    networks:
      - internal

networks:
  internal:
