version: '3'
services:
  server:
    build: ./server
    ports:
      - "${SERVER_PORT:-5000}:5000"
    environment:
      - FLASK_ENV=development
      - SERVER_PORT=${SERVER_PORT:-5000}
    depends_on:
      - influxdb
    networks:
      - internal
      - database-network

  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - database-network
    env_file:
      - influxdb/influxdb.env

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - database-network

networks:
  internal:
  database-network:

volumes:
  influxdb-storage:
  grafana-storage:
