version: '3'
services:
  server:
    build: ./server
    ports:
      - "${SERVER_PORT:-5000}:5000"
    environment:
      - FLASK_ENV=development
      - SERVER_PORT=${SERVER_PORT:-5000}
    depends_on:
      - influxdb
    networks:
      - internal
      - database-network

  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - database-network
    env_file:
      - influxdb/influxdb.env

  mock-client:
    build: ./mock-client
    environment:
      - SERVER_URL=http://server:${SERVER_PORT:-5000}
    depends_on:
      - server
    networks:
      - internal

networks:
  internal:
  database-network:

volumes:
  influxdb-storage:
