{
 "title": "DroN",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT MEAN(\"temp\") AS \"average_temperature\"\nFROM \"DroneMetrics\"\nWHERE time >= now() - 30m\nGROUP BY time(30s) fill(null)\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT MEAN(\"humidity\") AS humidity\nFROM \"DroneMetrics\"\nWHERE time >= now() - 30m\nGROUP BY time(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 8 },
   "targets": [
    {
     "query": "SELECT MEAN(\"heatIndex\") AS \"heatIndex\"\nFROM \"DroneMetrics\"\nWHERE time >= now() - 30m\nGROUP BY time(30s) fill(null)\n"
    }
   ]
  }
 ]
}